# Generated by Django 3.2.19 on 2023-06-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0002_categoria_devolucion_producto_entrada_producto_rol_salida_producto_tienda_trabajador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcionCategoria',
            new_name='descripcion',
        ),
    ]
