# Generated by Django 3.2.16 on 2023-06-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0002_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloApp.bodega'),
        ),
    ]
