# Generated by Django 3.2.19 on 2023-06-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0003_rename_descripcioncategoria_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloApp.categoria'),
        ),
    ]
