# Generated by Django 3.2.19 on 2023-06-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0005_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada_producto',
            old_name='descripcionEntrada',
            new_name='descripcion_Entrada',
        ),
        migrations.RenameField(
            model_name='entrada_producto',
            old_name='fechaEntrada',
            new_name='fecha_Entrada',
        ),
    ]
