# Generated by Django 3.2.19 on 2023-06-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0006_auto_20230620_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada_producto',
            old_name='descripcion_Entrada',
            new_name='descripcion_entrada',
        ),
        migrations.RenameField(
            model_name='entrada_producto',
            old_name='fecha_Entrada',
            new_name='fecha_entrada',
        ),
    ]
