# Generated by Django 3.2.16 on 2023-06-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0007_entrada_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada_Producto',
            new_name='Entrada',
        ),
    ]
