# Generated by Django 3.2.19 on 2023-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0007_auto_20230621_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('puede_realizar_accion', 'Puede realizar la acción')],
            },
        ),
    ]
